"""empty message

Revision ID: 37098ed4f8a1
Revises: d5aeaf1c5044
Create Date: 2023-04-23 19:12:25.866076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37098ed4f8a1'
down_revision = 'd5aeaf1c5044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('formatted_code_snippet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formatted_code_snippet', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
