"""Add code_snippet_language column to Comment table

Revision ID: 779114dff033
Revises: 37098ed4f8a1
Create Date: 2023-04-24 13:26:09.243059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779114dff033'
down_revision = '37098ed4f8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_snippet_language', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('code_snippet_language')

    # ### end Alembic commands ###
