"""empty message

Revision ID: d5aeaf1c5044
Revises: 
Create Date: 2023-04-23 14:07:51.309662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5aeaf1c5044'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_snippet_language', sa.String(length=20), nullable=True))
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('code_snippet_language')

    # ### end Alembic commands ###
